//============================================================================
// Name        : cparser.cpp
// Author      : Daniel Mosquera
// Version     :
// Copyright   : GPLv2
// Description : Hello World in C++, Ansi-style
//============================================================================

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <cparsertools.h>
#include <cparserpaths.h>
#include <cparsertoken.h>
#include <cparserobject.h>
#include <cparserdictionary.h>
#include <cparser.h>

int main()
{
	/* Obtained with command 'gcc -E -dM - < /dev/null' */
	cparserdictionary_t *defines = DictionaryNew();
	DictionarySetKeyValue(defines, _T "DEBUG", NULL);
	DictionarySetKeyValue(defines, _T "__SSP_STRONG__", ObjectNewPreprocessorExpression(_T "3"));
	DictionarySetKeyValue(defines, _T "__DBL_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-1021)"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MAX_EXP__", ObjectNewPreprocessorExpression(_T "1024"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST16_MAX__", ObjectNewPreprocessorExpression(_T "0xffff"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_ACQUIRE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT128_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "4932"));
	DictionarySetKeyValue(defines, _T "__FLT_MIN__", ObjectNewPreprocessorExpression(_T "1.17549435082228750796873653722224568e-38F"));
	DictionarySetKeyValue(defines, _T "__GCC_IEC_559_COMPLEX", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST8_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned char"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_FLOAT80__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__INTMAX_C(c)", ObjectNewPreprocessorExpression(_T "c ## L"));
	DictionarySetKeyValue(defines, _T "__CHAR_BIT__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__UINT8_MAX__", ObjectNewPreprocessorExpression(_T "0xff"));
	DictionarySetKeyValue(defines, _T "__WINT_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffU"));
	DictionarySetKeyValue(defines, _T "__FLT32_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-125)"));
	DictionarySetKeyValue(defines, _T "__ORDER_LITTLE_ENDIAN__", ObjectNewPreprocessorExpression(_T "1234"));
	DictionarySetKeyValue(defines, _T "__SIZE_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__WCHAR_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffff"));
	DictionarySetKeyValue(defines, _T "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DBL_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "((double)4.94065645841246544176568792868221372e-324L)"));
	DictionarySetKeyValue(defines, _T "__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_CHAR_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__GCC_IEC_559", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT32X_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "17"));
	DictionarySetKeyValue(defines, _T "__FLT_EVAL_METHOD__", ObjectNewPreprocessorExpression(_T "0"));
	DictionarySetKeyValue(defines, _T "__unix__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "17"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_CHAR32_T_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__x86_64", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST64_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__SIG_ATOMIC_TYPE__", ObjectNewPreprocessorExpression(_T "int"));
	DictionarySetKeyValue(defines, _T "__DBL_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-307)"));
	DictionarySetKeyValue(defines, _T "__FINITE_MATH_ONLY__", ObjectNewPreprocessorExpression(_T "0"));
	DictionarySetKeyValue(defines, _T "__GNUC_PATCHLEVEL__", ObjectNewPreprocessorExpression(_T "0"));
	DictionarySetKeyValue(defines, _T "__FLT32_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST8_MAX__", ObjectNewPreprocessorExpression(_T "0xff"));
	DictionarySetKeyValue(defines, _T "__has_include(STR)", ObjectNewPreprocessorExpression(_T "__has_include__(STR)"));
	DictionarySetKeyValue(defines, _T "__DEC64_MAX_EXP__", ObjectNewPreprocessorExpression(_T "385"));
	DictionarySetKeyValue(defines, _T "__INT8_C(c)", ObjectNewPreprocessorExpression(_T "c"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST8_WIDTH__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST64_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__SHRT_MAX__", ObjectNewPreprocessorExpression(_T "0x7fff"));
	DictionarySetKeyValue(defines, _T "__LDBL_MAX__", ObjectNewPreprocessorExpression(_T "1.18973149535723176502126385303097021e+4932L"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "4932"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST8_MAX__", ObjectNewPreprocessorExpression(_T "0xff"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_BOOL_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT128_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "6.47517511943802511092443895822764655e-4966F128"));
	DictionarySetKeyValue(defines, _T "__UINTMAX_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__linux", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC32_EPSILON__", ObjectNewPreprocessorExpression(_T "1E-6DF"));
	DictionarySetKeyValue(defines, _T "__FLT_EVAL_METHOD_TS_18661_3__", ObjectNewPreprocessorExpression(_T "0"));
	DictionarySetKeyValue(defines, _T "__unix", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__UINT32_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffU"));
	DictionarySetKeyValue(defines, _T "__LDBL_MAX_EXP__", ObjectNewPreprocessorExpression(_T "16384"));
	DictionarySetKeyValue(defines, _T "__FLT128_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-16381)"));
	DictionarySetKeyValue(defines, _T "__WINT_MIN__", ObjectNewPreprocessorExpression(_T "0U"));
	DictionarySetKeyValue(defines, _T "__linux__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT128_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-4931)"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST16_WIDTH__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__SCHAR_MAX__", ObjectNewPreprocessorExpression(_T "0x7f"));
	DictionarySetKeyValue(defines, _T "__FLT128_MANT_DIG__", ObjectNewPreprocessorExpression(_T "113"));
	DictionarySetKeyValue(defines, _T "__WCHAR_MIN__", ObjectNewPreprocessorExpression(_T "(-__WCHAR_MAX__ - 1)"));
	DictionarySetKeyValue(defines, _T "__INT64_C(c)", ObjectNewPreprocessorExpression(_T "c ## L"));
	DictionarySetKeyValue(defines, _T "__DBL_DIG__", ObjectNewPreprocessorExpression(_T "15"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_POINTER_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MANT_DIG__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_INT__", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_POINTER__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__USER_LABEL_PREFIX__", NULL);
	DictionarySetKeyValue(defines, _T "__FLT64X_EPSILON__", ObjectNewPreprocessorExpression(_T "1.08420217248550443400745280086994171e-19F64x"));
	DictionarySetKeyValue(defines, _T "__STDC_HOSTED__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__LDBL_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32_DIG__", ObjectNewPreprocessorExpression(_T "6"));
	DictionarySetKeyValue(defines, _T "__FLT_EPSILON__", ObjectNewPreprocessorExpression(_T "1.19209289550781250000000000000000000e-7F"));
	DictionarySetKeyValue(defines, _T "__SHRT_WIDTH__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__LDBL_MIN__", ObjectNewPreprocessorExpression(_T "3.36210314311209350626267781732175260e-4932L"));
	DictionarySetKeyValue(defines, _T "__STDC_UTF_16__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC32_MAX__", ObjectNewPreprocessorExpression(_T "9.999999E96DF"));
	DictionarySetKeyValue(defines, _T "__FLT64X_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "3.64519953188247460252840593361941982e-4951F64x"));
	DictionarySetKeyValue(defines, _T "__FLT32X_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT32_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffff"));
	DictionarySetKeyValue(defines, _T "__INT_WIDTH__", ObjectNewPreprocessorExpression(_T "32"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_LONG__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__STDC_IEC_559__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__STDC_ISO_10646__", ObjectNewPreprocessorExpression(_T "201706L"));
	DictionarySetKeyValue(defines, _T "__UINT16_C(c)", ObjectNewPreprocessorExpression(_T "c"));
	DictionarySetKeyValue(defines, _T "__PTRDIFF_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "21"));
	DictionarySetKeyValue(defines, _T "__FLT64_EPSILON__", ObjectNewPreprocessorExpression(_T "2.22044604925031308084726333618164062e-16F64"));
	DictionarySetKeyValue(defines, _T "__gnu_linux__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INTMAX_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__has_include_next(STR)", ObjectNewPreprocessorExpression(_T "__has_include_next__(STR)"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-4931)"));
	DictionarySetKeyValue(defines, _T "__LDBL_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_MANT_DIG__", ObjectNewPreprocessorExpression(_T "53"));
	DictionarySetKeyValue(defines, _T "__GNUC__", ObjectNewPreprocessorExpression(_T "7"));
	DictionarySetKeyValue(defines, _T "__pie__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__MMX__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_LONG_DOUBLE__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__BIGGEST_ALIGNMENT__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__FLT64_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "308"));
	DictionarySetKeyValue(defines, _T "__DBL_MAX__", ObjectNewPreprocessorExpression(_T "((double)1.79769313486231570814527423731704357e+308L)"));
	DictionarySetKeyValue(defines, _T "__INT_FAST32_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__DBL_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC32_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-94)"));
	DictionarySetKeyValue(defines, _T "__INTPTR_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__FLT32X_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT_FAST16_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__LDBL_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT128_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC128_MAX__", ObjectNewPreprocessorExpression(_T "9.999999999999999999999999999999999E6144DL"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST32_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffff"));
	DictionarySetKeyValue(defines, _T "__DEC32_MIN__", ObjectNewPreprocessorExpression(_T "1E-95DF"));
	DictionarySetKeyValue(defines, _T "__DBL_MAX_EXP__", ObjectNewPreprocessorExpression(_T "1024"));
	DictionarySetKeyValue(defines, _T "__WCHAR_WIDTH__", ObjectNewPreprocessorExpression(_T "32"));
	DictionarySetKeyValue(defines, _T "__FLT32_MAX__", ObjectNewPreprocessorExpression(_T "3.40282346638528859811704183484516925e+38F32"));
	DictionarySetKeyValue(defines, _T "__DEC128_EPSILON__", ObjectNewPreprocessorExpression(_T "1E-33DL"));
	DictionarySetKeyValue(defines, _T "__SSE2_MATH__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_HLE_RELEASE", ObjectNewPreprocessorExpression(_T "131072"));
	DictionarySetKeyValue(defines, _T "__PTRDIFF_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__amd64", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__STDC_NO_THREADS__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_HLE_ACQUIRE", ObjectNewPreprocessorExpression(_T "65536"));
	DictionarySetKeyValue(defines, _T "__FLT32_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__LONG_LONG_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffLL"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_SIZE_T__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-16381)"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_WINT_T__", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__LONG_LONG_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__FLT32_MAX_EXP__", ObjectNewPreprocessorExpression(_T "128"));
	DictionarySetKeyValue(defines, _T "__GCC_HAVE_DWARF2_CFI_ASM", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GXX_ABI_VERSION", ObjectNewPreprocessorExpression(_T "1011"));
	DictionarySetKeyValue(defines, _T "__FLT_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-125)"));
	DictionarySetKeyValue(defines, _T "__FLT64X_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT_FAST64_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__FLT64_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "4.94065645841246544176568792868221372e-324F64"));
	DictionarySetKeyValue(defines, _T "__DBL_MIN__", ObjectNewPreprocessorExpression(_T "((double)2.22507385850720138309023271733240406e-308L)"));
	DictionarySetKeyValue(defines, _T "__PIE__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__LP64__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32X_EPSILON__", ObjectNewPreprocessorExpression(_T "2.22044604925031308084726333618164062e-16F32x"));
	DictionarySetKeyValue(defines, _T "__DECIMAL_BID_FORMAT__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-1021)"));
	DictionarySetKeyValue(defines, _T "__FLT64_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-307)"));
	DictionarySetKeyValue(defines, _T "__FLT64X_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "21"));
	DictionarySetKeyValue(defines, _T "__DEC128_MIN__", ObjectNewPreprocessorExpression(_T "1E-6143DL"));
	DictionarySetKeyValue(defines, _T "__REGISTER_PREFIX__", NULL);
	DictionarySetKeyValue(defines, _T "__UINT16_MAX__", ObjectNewPreprocessorExpression(_T "0xffff"));
	DictionarySetKeyValue(defines, _T "__DBL_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32_MIN__", ObjectNewPreprocessorExpression(_T "1.17549435082228750796873653722224568e-38F32"));
	DictionarySetKeyValue(defines, _T "__UINT8_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned char"));
	DictionarySetKeyValue(defines, _T "__NO_INLINE__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT_MANT_DIG__", ObjectNewPreprocessorExpression(_T "24"));
	DictionarySetKeyValue(defines, _T "__LDBL_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "21"));
	DictionarySetKeyValue(defines, _T "__VERSION__", ObjectNewPreprocessorExpression(_T "\"7.4.0\""));
	DictionarySetKeyValue(defines, _T "__UINT64_C(c)", ObjectNewPreprocessorExpression(_T "c ## UL"));
	DictionarySetKeyValue(defines, _T "_STDC_PREDEF_H", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_INT_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT128_MAX_EXP__", ObjectNewPreprocessorExpression(_T "16384"));
	DictionarySetKeyValue(defines, _T "__FLT32_MANT_DIG__", ObjectNewPreprocessorExpression(_T "24"));
	DictionarySetKeyValue(defines, _T "__FLOAT_WORD_ORDER__", ObjectNewPreprocessorExpression(_T "__ORDER_LITTLE_ENDIAN__"));
	DictionarySetKeyValue(defines, _T "__STDC_IEC_559_COMPLEX__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT128_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT128_DIG__", ObjectNewPreprocessorExpression(_T "33"));
	DictionarySetKeyValue(defines, _T "__SCHAR_WIDTH__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__INT32_C(c)", ObjectNewPreprocessorExpression(_T "c"));
	DictionarySetKeyValue(defines, _T "__DEC64_EPSILON__", ObjectNewPreprocessorExpression(_T "1E-15DD"));
	DictionarySetKeyValue(defines, _T "__ORDER_PDP_ENDIAN__", ObjectNewPreprocessorExpression(_T "3412"));
	DictionarySetKeyValue(defines, _T "__DEC128_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-6142)"));
	DictionarySetKeyValue(defines, _T "__FLT32_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "38"));
	DictionarySetKeyValue(defines, _T "__INT_FAST32_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST16_TYPE__", ObjectNewPreprocessorExpression(_T "short unsigned int"));
	DictionarySetKeyValue(defines, _T "__FLT64X_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "unix", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT16_MAX__", ObjectNewPreprocessorExpression(_T "0x7fff"));
	DictionarySetKeyValue(defines, _T "__SIZE_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__UINT64_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__FLT64X_DIG__", ObjectNewPreprocessorExpression(_T "18"));
	DictionarySetKeyValue(defines, _T "__INT8_TYPE__", ObjectNewPreprocessorExpression(_T "signed char"));
	DictionarySetKeyValue(defines, _T "__ELF__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GCC_ASM_FLAG_OUTPUTS__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT_RADIX__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST16_TYPE__", ObjectNewPreprocessorExpression(_T "short int"));
	DictionarySetKeyValue(defines, _T "__LDBL_EPSILON__", ObjectNewPreprocessorExpression(_T "1.08420217248550443400745280086994171e-19L"));
	DictionarySetKeyValue(defines, _T "__UINTMAX_C(c)", ObjectNewPreprocessorExpression(_T "c ## UL"));
	DictionarySetKeyValue(defines, _T "__SSE_MATH__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__k8", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__SIG_ATOMIC_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffff"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_WCHAR_T_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_PTRDIFF_T__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MANT_DIG__", ObjectNewPreprocessorExpression(_T "53"));
	DictionarySetKeyValue(defines, _T "__x86_64__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-1021)"));
	DictionarySetKeyValue(defines, _T "__DEC32_SUBNORMAL_MIN__", ObjectNewPreprocessorExpression(_T "0.000001E-95DF"));
	DictionarySetKeyValue(defines, _T "__INT_FAST16_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__FLT64_DIG__", ObjectNewPreprocessorExpression(_T "15"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST32_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST64_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__FLT_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "38"));
	DictionarySetKeyValue(defines, _T "__LONG_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__FLT64X_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC128_SUBNORMAL_MIN__", ObjectNewPreprocessorExpression(_T "0.000000000000000000000000000000001E-6143DL"));
	DictionarySetKeyValue(defines, _T "__FLT_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST16_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__DEC64_MAX__", ObjectNewPreprocessorExpression(_T "9.999999999999999E384DD"));
	DictionarySetKeyValue(defines, _T "__INT_FAST32_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__CHAR16_TYPE__", ObjectNewPreprocessorExpression(_T "short unsigned int"));
	DictionarySetKeyValue(defines, _T "__PRAGMA_REDEFINE_EXTNAME", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__SIZE_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__SEG_FS", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST16_MAX__", ObjectNewPreprocessorExpression(_T "0x7fff"));
	DictionarySetKeyValue(defines, _T "__DEC64_MANT_DIG__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__INT64_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST32_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffU"));
	DictionarySetKeyValue(defines, _T "__SEG_GS", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "1.40129846432481707092372958328991613e-45F32"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_LONG_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__SIG_ATOMIC_WIDTH__", ObjectNewPreprocessorExpression(_T "32"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST64_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__INT16_TYPE__", ObjectNewPreprocessorExpression(_T "short int"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST8_TYPE__", ObjectNewPreprocessorExpression(_T "signed char"));
	DictionarySetKeyValue(defines, _T "__STDC_VERSION__", ObjectNewPreprocessorExpression(_T "201112L"));
	DictionarySetKeyValue(defines, _T "__DEC32_MAX_EXP__", ObjectNewPreprocessorExpression(_T "97"));
	DictionarySetKeyValue(defines, _T "__INT_FAST8_MAX__", ObjectNewPreprocessorExpression(_T "0x7f"));
	DictionarySetKeyValue(defines, _T "__FLT128_MAX__", ObjectNewPreprocessorExpression(_T "1.18973149535723176508575932662800702e+4932F128"));
	DictionarySetKeyValue(defines, _T "__INTPTR_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "linux", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-37)"));
	DictionarySetKeyValue(defines, _T "__SSE2__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32X_DIG__", ObjectNewPreprocessorExpression(_T "15"));
	DictionarySetKeyValue(defines, _T "__LDBL_MANT_DIG__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__DBL_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MAX__", ObjectNewPreprocessorExpression(_T "1.18973149535723176502126385303097021e+4932F64x"));
	DictionarySetKeyValue(defines, _T "__SIG_ATOMIC_MIN__", ObjectNewPreprocessorExpression(_T "(-__SIG_ATOMIC_MAX__- 1)"));
	DictionarySetKeyValue(defines, _T "__code_model_small__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__k8__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INTPTR_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__UINT16_TYPE__", ObjectNewPreprocessorExpression(_T "short unsigned int"));
	DictionarySetKeyValue(defines, _T "__WCHAR_TYPE__", ObjectNewPreprocessorExpression(_T "int"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_FLOAT__", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__pic__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__UINTPTR_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__INT_FAST64_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__DEC64_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-382)"));
	DictionarySetKeyValue(defines, _T "__FLT32_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "9"));
	DictionarySetKeyValue(defines, _T "__INT_FAST64_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_TEST_AND_SET_TRUEVAL", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT_DIG__", ObjectNewPreprocessorExpression(_T "6"));
	DictionarySetKeyValue(defines, _T "__FLT32_HAS_INFINITY__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MAX_EXP__", ObjectNewPreprocessorExpression(_T "16384"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST64_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__INT_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffff"));
	DictionarySetKeyValue(defines, _T "__amd64__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT64_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__FLT_MAX_EXP__", ObjectNewPreprocessorExpression(_T "128"));
	DictionarySetKeyValue(defines, _T "__ORDER_BIG_ENDIAN__", ObjectNewPreprocessorExpression(_T "4321"));
	DictionarySetKeyValue(defines, _T "__DBL_MANT_DIG__", ObjectNewPreprocessorExpression(_T "53"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_FLOAT128__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST64_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_CHAR16_T_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__DEC64_MIN__", ObjectNewPreprocessorExpression(_T "1E-383DD"));
	DictionarySetKeyValue(defines, _T "__WINT_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned int"));
	DictionarySetKeyValue(defines, _T "__UINT_LEAST32_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned int"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_SHORT__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__SSE__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__LDBL_MIN_EXP__", ObjectNewPreprocessorExpression(_T "(-16381)"));
	DictionarySetKeyValue(defines, _T "__FLT64_MAX__", ObjectNewPreprocessorExpression(_T "1.79769313486231570814527423731704357e+308F64"));
	DictionarySetKeyValue(defines, _T "__WINT_WIDTH__", ObjectNewPreprocessorExpression(_T "32"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST8_MAX__", ObjectNewPreprocessorExpression(_T "0x7f"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "308"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_INT128__", ObjectNewPreprocessorExpression(_T "16"));
	DictionarySetKeyValue(defines, _T "__LDBL_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "4932"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_RELAXED", ObjectNewPreprocessorExpression(_T "0"));
	DictionarySetKeyValue(defines, _T "__DBL_EPSILON__", ObjectNewPreprocessorExpression(_T "((double)2.22044604925031308084726333618164062e-16L)"));
	DictionarySetKeyValue(defines, _T "__FLT128_MIN__", ObjectNewPreprocessorExpression(_T "3.36210314311209350626267781732175260e-4932F128"));
	DictionarySetKeyValue(defines, _T "_LP64", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__UINT8_C(c)", ObjectNewPreprocessorExpression(_T "c"));
	DictionarySetKeyValue(defines, _T "__FLT64_MAX_EXP__", ObjectNewPreprocessorExpression(_T "1024"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST32_TYPE__", ObjectNewPreprocessorExpression(_T "int"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_WCHAR_T__", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__UINT64_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__FLT128_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT_FAST8_TYPE__", ObjectNewPreprocessorExpression(_T "signed char"));
	DictionarySetKeyValue(defines, _T "__FLT64X_MIN__", ObjectNewPreprocessorExpression(_T "3.36210314311209350626267781732175260e-4932F64x"));
	DictionarySetKeyValue(defines, _T "__GNUC_STDC_INLINE__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT64_HAS_DENORM__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__FLT32_EPSILON__", ObjectNewPreprocessorExpression(_T "1.19209289550781250000000000000000000e-7F32"));
	DictionarySetKeyValue(defines, _T "__DBL_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "17"));
	DictionarySetKeyValue(defines, _T "__STDC_UTF_32__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__INT_FAST8_WIDTH__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__FXSR__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__DEC_EVAL_METHOD__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MAX__", ObjectNewPreprocessorExpression(_T "1.79769313486231570814527423731704357e+308F32x"));
	DictionarySetKeyValue(defines, _T "__UINT32_C(c)", ObjectNewPreprocessorExpression(_T "c ## U"));
	DictionarySetKeyValue(defines, _T "__INTMAX_MAX__", ObjectNewPreprocessorExpression(_T "0x7fffffffffffffffL"));
	DictionarySetKeyValue(defines, _T "__BYTE_ORDER__", ObjectNewPreprocessorExpression(_T "__ORDER_LITTLE_ENDIAN__"));
	DictionarySetKeyValue(defines, _T "__FLT_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "1.40129846432481707092372958328991613e-45F"));
	DictionarySetKeyValue(defines, _T "__INT8_MAX__", ObjectNewPreprocessorExpression(_T "0x7f"));
	DictionarySetKeyValue(defines, _T "__LONG_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__PIC__", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST32_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__CHAR32_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned int"));
	DictionarySetKeyValue(defines, _T "__FLT_MAX__", ObjectNewPreprocessorExpression(_T "3.40282346638528859811704183484516925e+38F"));
	DictionarySetKeyValue(defines, _T "__INT32_TYPE__", ObjectNewPreprocessorExpression(_T "int"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_DOUBLE__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__FLT_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-37)"));
	DictionarySetKeyValue(defines, _T "__FLT64_MIN__", ObjectNewPreprocessorExpression(_T "2.22507385850720138309023271733240406e-308F64"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST32_WIDTH__", ObjectNewPreprocessorExpression(_T "32"));
	DictionarySetKeyValue(defines, _T "__INTMAX_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__DEC128_MAX_EXP__", ObjectNewPreprocessorExpression(_T "6145"));
	DictionarySetKeyValue(defines, _T "__FLT32X_HAS_QUIET_NAN__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_CONSUME", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__GNUC_MINOR__", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__INT_FAST16_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__UINTMAX_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__DEC32_MANT_DIG__", ObjectNewPreprocessorExpression(_T "7"));
	DictionarySetKeyValue(defines, _T "__FLT32X_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "4.94065645841246544176568792868221372e-324F32x"));
	DictionarySetKeyValue(defines, _T "__DBL_MAX_10_EXP__", ObjectNewPreprocessorExpression(_T "308"));
	DictionarySetKeyValue(defines, _T "__LDBL_DENORM_MIN__", ObjectNewPreprocessorExpression(_T "3.64519953188247460252840593361941982e-4951L"));
	DictionarySetKeyValue(defines, _T "__INT16_C(c)", ObjectNewPreprocessorExpression(_T "c"));
	DictionarySetKeyValue(defines, _T "__STDC__", ObjectNewPreprocessorExpression(_T "1"));
	DictionarySetKeyValue(defines, _T "__PTRDIFF_TYPE__", ObjectNewPreprocessorExpression(_T "long int"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_SEQ_CST", ObjectNewPreprocessorExpression(_T "5"));
	DictionarySetKeyValue(defines, _T "__UINT32_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned int"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-307)"));
	DictionarySetKeyValue(defines, _T "__UINTPTR_TYPE__", ObjectNewPreprocessorExpression(_T "long unsigned int"));
	DictionarySetKeyValue(defines, _T "__DEC64_SUBNORMAL_MIN__", ObjectNewPreprocessorExpression(_T "0.000000000000001E-383DD"));
	DictionarySetKeyValue(defines, _T "__DEC128_MANT_DIG__", ObjectNewPreprocessorExpression(_T "34"));
	DictionarySetKeyValue(defines, _T "__LDBL_MIN_10_EXP__", ObjectNewPreprocessorExpression(_T "(-4931)"));
	DictionarySetKeyValue(defines, _T "__FLT128_EPSILON__", ObjectNewPreprocessorExpression(_T "1.92592994438723585305597794258492732e-34F128"));
	DictionarySetKeyValue(defines, _T "__SIZEOF_LONG_LONG__", ObjectNewPreprocessorExpression(_T "8"));
	DictionarySetKeyValue(defines, _T "__FLT128_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "36"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_LLONG_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__FLT32X_MIN__", ObjectNewPreprocessorExpression(_T "2.22507385850720138309023271733240406e-308F32x"));
	DictionarySetKeyValue(defines, _T "__LDBL_DIG__", ObjectNewPreprocessorExpression(_T "18"));
	DictionarySetKeyValue(defines, _T "__FLT_DECIMAL_DIG__", ObjectNewPreprocessorExpression(_T "9"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST16_MAX__", ObjectNewPreprocessorExpression(_T "0xffffffffffffffffUL"));
	DictionarySetKeyValue(defines, _T "__GCC_ATOMIC_SHORT_LOCK_FREE", ObjectNewPreprocessorExpression(_T "2"));
	DictionarySetKeyValue(defines, _T "__INT_LEAST64_WIDTH__", ObjectNewPreprocessorExpression(_T "64"));
	DictionarySetKeyValue(defines, _T "__UINT_FAST8_TYPE__", ObjectNewPreprocessorExpression(_T "unsigned char"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_ACQ_REL", ObjectNewPreprocessorExpression(_T "4"));
	DictionarySetKeyValue(defines, _T "__ATOMIC_RELEASE", ObjectNewPreprocessorExpression(_T "3"));

	/* Obtained with command 'gcc -E -Wp,-v - < /dev/null' */
	cparserpaths_t *cpaths = PathsNew();
	PathsAddPath(cpaths,_T "/usr/lib/gcc/x86_64-linux-gnu/7/include");
	PathsAddPath(cpaths,_T "/usr/local/include");
	PathsAddPath(cpaths,_T "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed");
	PathsAddPath(cpaths,_T "/usr/include/x86_64-linux-gnu");
	PathsAddPath(cpaths,_T "/usr/include");
	PathsAddPath(cpaths,_T "./src/");
	PathsAddPath(cpaths,_T "./src/cparser");
	PathsAddPath(cpaths,_T ".");

	object_t *oo = CParserParse(defines, cpaths, _T"project_examples/opengl/main.c");

	printf("Fin.\r\n");

	return 0;
}

